// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhpaatqvxvmcmjxcfdud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocGFhdHF2eHZtY21qeGNmZHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODM1NDksImV4cCI6MjA2ODU1OTU0OX0.XXYHvxs5EwFIO_yPdVycGs3kyytE0OpH-X5lXXvWziE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});